config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'foods#index', as: :authenticated_root
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :recipes, only: [:index, :new, :create, :show, :destroy] do
      member do
        patch 'toggle'
        get 'shopping_list'
      end
      resources :foods, only: [:new, :create]
      resources :recipe_foods, only: [:new, :create, :destroy]
    end

    get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes
    get 'shopping_list', to: 'recipes#shopping_list'
  end

  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :user_id, presence: true

  def calculate_total_amount
    total_amount = 0
    recipe_foods.each do |recipe_food|
      total_amount += recipe_food.food.price * recipe_food.quantity
    end
    total_amount
  end

  scope :public_recipes, -> { where(public: true) }

  def public?
    public
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :food, uniqueness: { scope: :recipe_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  accepts_nested_attributes_for :foods
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.includes(:user)
  end

  def new
    @food = current_user.foods.build
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully added.'
    else
      render :new
    end
  end

  def edit
    @food = current_user.foods.find(params[:id])
  end

  def update
    @food = current_user.foods.find(params[:id])
    if @food.update(food_params)
      redirect_to foods_path, notice: 'Food successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food successfully deleted.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: [:destroy]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    if @recipe.user == current_user && @recipe_food.save
      flash[:success] = 'Ingredient successfully added'
      redirect_to @recipe
    else
      @foods = Food.all
      flash[:error] = 'Error adding ingredient'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to recipe_url, notice: 'Recipe food was successfully destroyed.'
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :authorize_recipe_toggle, only: [:toggle]

  def index
    @recipes = if user_signed_in?
                 current_user.recipes.includes(:user)
               else
                 Recipe.where(public: true)
               end

    @recipes = @recipes.order(created_at: :desc)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.public = false

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully.'
    else
      render :new
    end
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)

    if @recipe.public?
      session[:public_recipes] ||= []
      session[:public_recipes] << @recipe.id
    elsif session[:public_recipes]
      session[:public_recipes].delete(@recipe.id)
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
    end
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  def shopping_list
    @recipes = current_user.recipes.includes(:recipe_foods)
    @missing_foods = find_missing_foods
    @total_items = @missing_foods.pluck(:quantity).sum
    @total_price = calculate_total_price(@missing_foods)
  end

  private

  def authorize_recipe_toggle
    @recipe = Recipe.find(params[:id])
    return if @recipe.user_id == current_user.id

    flash[:error] = 'You are not authorized to perform this action.'
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end

  def find_missing_foods
    missing_foods = []
    @recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        missing_quantity = recipe_food.quantity
        missing_foods << recipe_food if missing_quantity&.positive?
      end
    end
    missing_foods
  end

  def calculate_total_price(missing_foods)
    total_price = 0
    missing_foods.each do |recipe_food|
      total_price += recipe_food.quantity * recipe_food.food.price
    end
    total_price
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/foods/index.html.erb
<div class="flex flex-col items-center mt-8  sm:w-4/5 mx-auto">
  <h1 class="text-2xl  font-bold mb-6">Food List</h1>
  <%= link_to 'Add New Food', new_food_path, class: "py-2 px-3 border border-[#81bab4] self-end rounded-md" %>
  <% if @foods.empty? %>
    <p class="mt-5">No foods added.</p>
  <% else %>
    <div class="overflow-x-auto w-full mt-8">
      <table class="w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th class="py-3 px-6 text-left bg-gray-50 font-bold text-gray-500">
              Name
            </th>
            <th class="py-3 px-6 text-left bg-gray-50 font-bold text-gray-500">
              Measurement Unit
            </th>
            <th class="py-3 px-6 text-left bg-gray-50 font-bold text-gray-500">
              Unit Price
            </th>
            <th class="py-3 px-6 text-left bg-gray-50 font-bold text-gray-500">
              Actions
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <% @foods.each do |food| %>
            <tr>
              <td class="py-3 px-6 whitespace-nowrap">
                <%= food.name %>
              </td>
              <td class="py-3 px-6 whitespace-nowrap">
                <%= food.measurement_unit %>
              </td>
              <td class="py-3 px-6 whitespace-nowrap">
                <%= food.price %>
              </td>
              <td class="py-3 px-6 whitespace-nowrap">
                <% if current_user == food.user %>
                  <%= button_to "Delete", food_path(food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class="flex flex-col items-center mt-14">
  <h1 class="mb-14 font-bold">Add New Food</h1>

  <%= form_with model: @food, url: foods_path, class: ' w-full max-w-sm' do |form| %>
    <div class="mb-4">
      <%= form.label :name, class: 'text-gray-700 font-bold mb-2' %>
      <%= form.text_field :name, class: 'w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300' %>
    </div>

    <div class="mb-4">
      <%= form.label :measurement_unit, class: 'text-gray-700 font-bold mb-2' %>
      <%= form.text_field :measurement_unit, class: 'w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300' %>
    </div>

    <div class="mb-4">
      <%= form.label :price, class: 'text-gray-700 font-bold mb-2' %>
      <%= form.text_field :price, class: 'w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300' %>
    </div>

    <div class="w-full mt-5">
      <%= form.submit 'Add Food', class: 'w-full bg-[#81bab4] py-2 rounded-md text-white shadow-md cursor-pointer' %>
    </div>

    <%= link_to 'Back to Food List', foods_path, class: 'text-gray-600 underline mt-5' %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Recipe App</h1>

<%= link_to 'Login', new_user_session_path %>
<%= link_to 'Sign-up', new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full">

<nav class="flex justify-between sm:block  py-4 px-6 sm:px-12">
  <div class="flex sm:items-center sm:justify-between flex-col sm:flex-row w-full">
    <% if user_signed_in? %>
      <div class="mr-6">
        <%= link_to "Our Recipes", foods_path, class: "text-gray-800 font-semibold" %>
      </div>
    <% else %>
      <div class="mr-6">
        <%= link_to "Our Recipes", new_user_session_path, class: "text-gray-800 font-semibold" %>
      </div>
    <% end %>

    <ul class="sm:flex flex-col sm:flex-row sm:items-center sm:space-x-4 sm:space-y-0 hidden text-center pt-8 m-2 sm:m-0 sm:p-0" id="nav-menu">
      <% if user_signed_in? %>
        <li>
          <%= link_to "Recipe List", recipes_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
        <li>
          <%= link_to "Public Recipes", public_recipes_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
        <li>
          <%= link_to "Shopping List", shopping_list_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
        <li>
          <%= link_to 'Foods', foods_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
        <li>
          <%= form_for(current_user, url: destroy_user_session_path, method: :delete, html: { class: "" }) do |f| %>
            <%= f.submit "Logout", class: "text-gray-800 hover:text-gray-700 cursor-pointer" %>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path, class: "text-gray-800 hover:text-gray-700" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="block sm:hidden">
    <button class="flex items-center px-3 py-2 rounded text-gray-800 hover:text-gray-700 focus:outline-none focus:text-gray-700" id="nav-toggle">
      <svg class="h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 4.25C0 3.55964 0.559644 3 1.25 3H18.75C19.4404 3 20 3.55964 20 4.25C20 4.94036 19.4404 5.5 18.75 5.5H1.25C0.559644 5.5 0 4.94036 0 4.25ZM0 9.75C0 9.05964 0.559644 8.5 1.25 8.5H18.75C19.4404 8.5 20 9.05964 20 9.75C20 10.4404 19.4404 11 18.75 11H1.25C0.559644 11 0 10.4404 0 9.75ZM0 15.25C0 14.5596 0.559644 14 1.25 14H18.75C19.4404 14 20 14.5596 20 15.25C20 15.9404 19.4404 16.5 18.75 16.5H1.25C0.559644 16.5 0 15.9404 0 15.25Z"></path>
      </svg>
    </button>
  </div>


</nav>


    <%= yield %> 
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="error"><%= flash[:error] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="error"><%= alert %></div>
    <% end %>

    <script>
  document.getElementById('nav-toggle').addEventListener('click', function() {
    var navMenu = document.getElementById('nav-menu');
    if (navMenu.classList.contains('hidden')) {
      navMenu.classList.remove('hidden');
    } else {
      navMenu.classList.add('hidden');
    }
  });
</script>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="flex flex-col items-center mt-14">
  <h1 class="text-2xl font-bold mb-8">Add New Ingredient</h1>

  <% if flash[:error].present? %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with(model: [@recipe, @recipe_food], local: true, class: "w-full max-w-sm") do |form| %>
    <div class="mb-4">
      <%= form.label :food_id, "Food", class: "block font-bold mb-2" %>
      <%= form.collection_select :food_id, @foods, :id, :name, { prompt: "Select food item" }, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :quantity, "Quantity", class: "block font-bold mb-2" %>
      <%= form.number_field :quantity, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="flex justify-between gap-4">
      <%= form.submit "Add Ingredient", class: "w-full px-4 py-2 bg-[#81bab4] text-white font-semibold rounded-md shadow-md focus:outline-none focus:ring focus:ring-blue-300 cursor-pointer" %>
      <%= link_to "Cancel", recipe_path(@recipe), class: "w-full px-4 py-2 text-center text-gray-600 bg-gray-200 rounded-md hover:bg-gray-300" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="flex flex-col items-center w-full mx-auto mt-8 sm:w-4/5">
  <h1 class="mb-8 font-bold text-center text-2xl ">Recipes</h1>
  <% if user_signed_in? %>
    <%= link_to 'Create New Recipe', new_recipe_path, class: "py-2 px-3 border border-[#81bab4] self-end rounded-md" %>
  <% end %>

  <% if @recipes.any? %>
    <ul class="w-full mt-8">
      <% @recipes.each do |recipe| %>
        <li class="bg-white shadow-md rounded-md p-6 mb-6 border border-[#81bab4]  ">
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-lg font-bold capitalize"><%= link_to recipe.name, recipe_path(recipe), class: 'text-blue-600 hover:underline' %></h2>
          <p class="text-gray-600"><%= recipe.description %></p>
          </div>
            <% if recipe.user == current_user %>
              <%= button_to 'Remove', recipe, method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' }, class: 'text-red-600 hover:underline' %>
            <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-gray-600">No recipes found.</p>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="flex flex-col items-center mt-14">
  <h1 class="text-2xl font-bold mb-8">New Recipe</h1>

  <%= form_with(model: @recipe, url: recipes_path, local: true, class: "w-full max-w-sm") do |form| %>
    <div class="mb-4">
      <%= form.label :name, class: "block font-bold mb-2" %>
      <%= form.text_field :name, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :cooking_time, class: "block font-bold mb-2" %>
      <%= form.text_field :cooking_time, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :preparation_time, class: "block font-bold mb-2" %>
      <%= form.text_field :preparation_time, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, class: "block font-bold mb-2" %>
      <%= form.text_field :description, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-blue-300" %>
    </div>

    <div class="flex justify-end">
      <%= form.submit "Create Recipe", class: " w-full px-4 py-2 bg-[#81bab4] text-white font-semibold rounded-md shadow-md focus:outline-none focus:ring focus:ring-blue-300 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="flex flex-col items-center w-full mx-auto mt-8 sm:w-4/5">
  <h1 class="text-2xl font-bold mb-8">Public Recipes</h1>

  <% @public_recipes.each do |recipe| %>
    <div class="bg-white shadow-md rounded-md p-6 mb-6 border border-[#81bab4] w-full flex justify-between   ">
      <div>

      <h3 class="text-lg font-bold capitalize"><%= recipe.name %></h3>
      <p class="text-gray-600">Author: <%= recipe.user.name %></p>
      </div>
      <div>

      <p class="text-gray-600">Total Food Items: <%= recipe.recipe_foods.count %></p>
      <p class="text-gray-600">Total Amount: $<%= recipe.calculate_total_amount %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<div class="flex flex-col min-h-screen sm:w-4/5 mx-auto">
  

    <div class="flex flex-col items-center mt-8">
      <h1 class="text-2xl font-bold mb-8">Shopping List</h1>

        <div class="my-4 flex justify-between gap-10">
    <p>Amount of food items to buy: <%= @missing_foods.size %></p>
    <p>Total value of food needed: <%= number_to_currency(@total_price) %></p>
  </div>

      <% if @missing_foods.empty? %>
        <p>No missing food items.</p>
      <% else %>
        <div class="w-full overflow-x-auto">
          <table class="w-full text-center">
  <thead>
    <tr>
      <th class="py-2 px-4 bg-gray-200">Food</th>
      <th class="py-2 px-4 bg-gray-200">Quantity</th>
      <th class="py-2 px-4 bg-gray-200">Price</th>
    </tr>
  </thead>
  <tbody>
    <% @missing_foods.each do |missing_food| %>
      <tr>
        <td class="py-2 px-4"><%= missing_food.food.name %></td>
        <td class="py-2 px-4"><%= missing_food.quantity %></td>
        <td class="py-2 px-4"><%= number_to_currency(missing_food.food.price * missing_food.quantity) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th class="py-2 px-4">Total</th>
      <th class="py-2 px-4"><%= @total_items %></th>
      <th class="py-2 px-4"><%= number_to_currency(@total_price) %></th>
    </tr>
  </tfoot>
</table>

        </div>
      <% end %>
    </div>


</div>

app/views/recipes/show.html.erb
<main class="p-8 sm:w-4/5 mx-auto">
  <h3 class="text-xl font-bold mb-4 text-center capitalize"><%= @recipe.name %></h3>

  <section class="flex justify-between">
    <div class="mb-8">
      <div>
        <p class="mb-2">Preparation Time: <%= @recipe.preparation_time %> hour</p>
        <p class="mb-2">Cooking Time: <%= @recipe.cooking_time %> hour</p>
        <p class="mb-2"><%= @recipe.description %></p>
      </div>
    </div>
    <div class="flex gap-2">
  <p>Public</p>
<div class="relative inline-block w-12 h-6 mr-2 align-middle select-none bg-slate-500 rounded-2xl">
  <% if @recipe.user_id == current_user.id %>
    <%= form_with model: @recipe, url: toggle_recipe_path(@recipe), method: :patch, local: true do |form| %>
      <% new_public_status = !@recipe.public %>
      <button type="submit" class="toggle-switch absolute block w-6 h-6 rounded-full bg-gray-300 transition-transform duration-300 ease-in-out <%= @recipe.public ? 'translate-x-full bg-green-400' : 'translate-x-0 bg-gray-300' %>">
        <span class="sr-only">Toggle</span>
      </button>
      <%= form.hidden_field :public, value: new_public_status %>
    <% end %>
  <% end %>
</div>
      </div>


  </section>
  
  <section class="my-4 flex justify-between">
    <%= link_to 'Generate Shopping List', shopping_list_path, class: 'py-2 px-3 border border-[#81bab4] self-end rounded-md' %>
    <% if @recipe.user == current_user %>
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe), class: 'py-2 px-3 border border-[#81bab4] self-end rounded-md' %>
    <% end %>
  </section>
  
  <table class="w-full">
    <thead>
      <tr>
        <th class="py-2 px-4 bg-gray-100 font-bold">Food</th>
        <th class="py-2 px-4 bg-gray-100 font-bold">Quantity</th>
        <th class="py-2 px-4 bg-gray-100 font-bold">Value</th>
        <th class="py-2 px-4 bg-gray-100 font-bold">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <% food = recipe_food.food %>
        <tr>
          <td class="py-2 px-4"><%= food.name %></td>
          <td class="py-2 px-4"><%= recipe_food.quantity %> <%= food.measurement_unit %></td>
          <td class="py-2 px-4">$<%= food.price * recipe_food.quantity %></td>
          <td class="py-2 px-4">
            <% if @recipe.user == current_user %>
              <%= link_to 'Modify', '#', class: 'text-blue-500 underline mr-2' %>
            <% end %> 
            <% if @recipe.user == current_user %>
              <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'text-red-500 underline' %>
            <% end %>  
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>